### ISSUE TITLE
Cert request failing with CNAME

### ISSUE THREAD

**Issue by mhaluska** [jahudka/certbot-dns-active24#8]
Plugin is failing when using CNAME DNS entry like `*.subdomain.domain.com` and requesting same wild cert.
Works fine with enough time defined in `--dns-active24-propagation-seconds`.

certbot-1.12.0-1.el8.noarch
certbot-dns-active24 (1.2.0)

DNS record before TXT is propagated:
```
% host -t TXT _acme-challenge.subdomain.domain.com
_acme-challenge.subdomain.domain.com is an alias for subdomain.domain.com.
```

Certbot command:
```
# certbot certonly --dry-run -a dns-active24 -d *.subdomain.domain.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-active24, Installer None
Simulating a certificate request for ***
Performing the following challenges:
dns-01 challenge for ***
Waiting 0 seconds for DNS changes to propagate
Cleaning up challenges
An unexpected error occurred:
AttributeError: 'CNAME' object has no attribute 'strings'
Please see the logfiles in /var/log/letsencrypt for more details.
```

Log output:
```
2021-02-25 13:33:50,069:DEBUG:certbot_dns_active24.dns_active24:Waiting for propagation to authoritative servers
2021-02-25 13:33:50,074:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 62, in perform
    _wait_for_propagation(achalls)
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 91, in _wait_for_propagation
    queue = [(ns, content, query) for (ns, content, query) in queue if not _check_nameserver(ns, query, content)]
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 91, in <listcomp>
    queue = [(ns, content, query) for (ns, content, query) in queue if not _check_nameserver(ns, query, content)]
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 105, in _check_nameserver
    strings = [s.decode('utf-8') for r in result.answer for a in r for s in a.strings]
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 105, in <listcomp>
    strings = [s.decode('utf-8') for r in result.answer for a in r for s in a.strings]
AttributeError: 'CNAME' object has no attribute 'strings'

2021-02-25 13:33:50,074:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-02-25 13:33:50,074:INFO:certbot._internal.auth_handler:Cleaning up challenges
...
...
...
2021-02-25 13:33:52,225:DEBUG:certbot_dns_active24.dns_active24:Record doesn't appear to exist, aborting
2021-02-25 13:33:52,225:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.12.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 1413, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 1293, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 134, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 441, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 421, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 62, in perform
    _wait_for_propagation(achalls)
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 91, in _wait_for_propagation
    queue = [(ns, content, query) for (ns, content, query) in queue if not _check_nameserver(ns, query, content)]
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 91, in <listcomp>
    queue = [(ns, content, query) for (ns, content, query) in queue if not _check_nameserver(ns, query, content)]
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 105, in _check_nameserver
    strings = [s.decode('utf-8') for r in result.answer for a in r for s in a.strings]
  File "/usr/local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 105, in <listcomp>
    strings = [s.decode('utf-8') for r in result.answer for a in r for s in a.strings]
AttributeError: 'CNAME' object has no attribute 'strings'
2021-02-25 13:33:52,226:ERROR:certbot._internal.log:An unexpected error occurred:
2021-02-25 13:33:52,226:ERROR:certbot._internal.log:AttributeError: 'CNAME' object has no attribute 'strings'
```

**Comment by jahudka** [comment]
Hi, thanks for the report, I'll look into it, although I can't promise a timetable right now - if you wish, I'd be happy to accept a pull request, of course, but otherwise it might take a couple of days, sorry!

**Comment by mhaluska** [comment]
Hi, I'm not python dev, so cannot help here. This is not urgent, I can still use `--dns-active24-propagation-seconds`. Thanks
